function changeimg(el){ //Tiamat
	if (document.getElementById("picture").src.match("images/white.png") && document.getElementById("title").innerHTML == "White Chromatic Dragon" && document.getElementById("description").innerHTML == "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky."){ //checks which picture it is
		document.getElementById("picture").src = "images/tiamat.jpg"; //switches current image
		document.getElementById("title").innerHTML = "Tiamat the Dragon Queen";//switches current title
		document.getElementById("description").innerHTML = "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power.";
	}else if(document.getElementById("picture").src.match("images/black.png") && document.getElementById("title").innerHTML == "Black Chromatic Dragon" && document.getElementById("description").innerHTML == "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home."){
		document.getElementById("picture").src = "images/tiamat.jpg";
		document.getElementById("title").innerHTML = "Tiamat the Dragon Queen";
		document.getElementById("description").innerHTML = "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power.";
	}else if(document.getElementById("picture").src.match("images/blue.png") && document.getElementById("title").innerHTML == "Blue Chromatic Dragon" && document.getElementById("description").innerHTML == "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air."){
		document.getElementById("picture").src = "images/tiamat.jpg";
		document.getElementById("title").innerHTML = "Tiamat the Dragon Queen";
		document.getElementById("description").innerHTML = "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power.";
	}else if(document.getElementById("picture").src.match("images/red.png") && document.getElementById("title").innerHTML == "Red Chromatic Dragon" && document.getElementById("description").innerHTML == "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs."){
		document.getElementById("picture").src = "images/tiamat.jpg";
		document.getElementById("title").innerHTML = "Tiamat the Dragon Queen";
		document.getElementById("description").innerHTML = "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power.";
	}else if(document.getElementById("picture").src.match("images/green.png") && document.getElementById("title").innerHTML == "Green Chromatic Dragon" && document.getElementById("description").innerHTML == "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up."){
		document.getElementById("picture").src = "images/tiamat.jpg";
		document.getElementById("title").innerHTML = "Tiamat the Dragon Queen";
		document.getElementById("description").innerHTML = "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power.";
	}else {
		
	}
}

function changeimg1(el){ //White Dragon
	if (document.getElementById("picture").src.match("images/tiamat.jpg") && document.getElementById("title").innerHTML == "Tiamat the Dragon Queen" && document.getElementById("description").innerHTML == "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power."){ //checks which picture it is
		document.getElementById("picture").src = "images/white.png"; //changes current image to White Dragon
		document.getElementById("title").innerHTML = "White Chromatic Dragon";
		document.getElementById("description").innerHTML = "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky.";
	}else if(document.getElementById("picture").src.match("images/black.png") && document.getElementById("title").innerHTML == "Black Chromatic Dragon" && document.getElementById("description").innerHTML == "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home."){
		document.getElementById("picture").src = "images/white.png";
		document.getElementById("title").innerHTML = "White Chromatic Dragon";
		document.getElementById("description").innerHTML = "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky.";
	}else if(document.getElementById("picture").src.match("images/blue.png") && document.getElementById("title").innerHTML == "Blue Chromatic Dragon" && document.getElementById("description").innerHTML == "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air."){
		document.getElementById("picture").src = "images/white.png";
		document.getElementById("title").innerHTML = "White Chromatic Dragon";
		document.getElementById("description").innerHTML = "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky.";
	}else if(document.getElementById("picture").src.match("images/red.png") && document.getElementById("title").innerHTML == "Red Chromatic Dragon" && document.getElementById("description").innerHTML == "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs."){
		document.getElementById("picture").src = "images/white.png";
		document.getElementById("title").innerHTML = "White Chromatic Dragon";
		document.getElementById("description").innerHTML = "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky.";
	}else if(document.getElementById("picture").src.match("images/green.png") && document.getElementById("title").innerHTML == "Green Chromatic Dragon" && document.getElementById("description").innerHTML == "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up."){
		document.getElementById("picture").src = "images/white.png";
		document.getElementById("title").innerHTML = "White Chromatic Dragon";
		document.getElementById("description").innerHTML = "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky.";
	}else {
		
	}
}

function changeimg2 (el){ //Black Dragon
	if (document.getElementById("picture").src.match("images/tiamat.jpg") && document.getElementById("title").innerHTML == "Tiamat the Dragon Queen" && document.getElementById("description").innerHTML == "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power."){ //checks which picture it is
		document.getElementById("picture").src = "images/black.png"; //changes current image to Black Dragon
		document.getElementById("title").innerHTML = "Black Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home.";
	}else if(document.getElementById("picture").src.match("images/white.png") && document.getElementById("title").innerHTML == "White Chromatic Dragon" && document.getElementById("description").innerHTML == "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky."){
		document.getElementById("picture").src = "images/black.png";
		document.getElementById("title").innerHTML = "Black Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home.";
	}else if(document.getElementById("picture").src.match("images/blue.png") && document.getElementById("title").innerHTML == "Blue Chromatic Dragon" && document.getElementById("description").innerHTML == "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air."){
		document.getElementById("picture").src = "images/black.png";
		document.getElementById("title").innerHTML = "Black Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home.";
	}else if(document.getElementById("picture").src.match("images/red.png") && document.getElementById("title").innerHTML == "Red Chromatic Dragon" && document.getElementById("description").innerHTML == "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs."){
		document.getElementById("picture").src = "images/black.png";
		document.getElementById("title").innerHTML = "Black Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home.";
	}else if(document.getElementById("picture").src.match("images/green.png") && document.getElementById("title").innerHTML == "Green Chromatic Dragon" && document.getElementById("description").innerHTML == "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up."){
		document.getElementById("picture").src = "images/black.png";
		document.getElementById("title").innerHTML = "Black Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home.";
	}else {
		
	}
}

function changeimg3 (el){ //Blue Dragon
	if (document.getElementById("picture").src.match("images/tiamat.jpg") && document.getElementById("title").innerHTML == "Tiamat the Dragon Queen" && document.getElementById("description").innerHTML == "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power."){ //checks which picture it is
		document.getElementById("picture").src = "images/blue.png"; //changes current image to Blue Dragon
		document.getElementById("title").innerHTML = "Blue Chromatic Dragon";
		document.getElementById("description").innerHTML = "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air.";
	}else if(document.getElementById("picture").src.match("images/white.png") && document.getElementById("title").innerHTML == "White Chromatic Dragon" && document.getElementById("description").innerHTML == "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky."){
		document.getElementById("picture").src = "images/blue.png";
		document.getElementById("title").innerHTML = "Blue Chromatic Dragon";
		document.getElementById("description").innerHTML = "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air.";
	}else if(document.getElementById("picture").src.match("images/black.png") && document.getElementById("title").innerHTML == "Black Chromatic Dragon" && document.getElementById("description").innerHTML == "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home."){
		document.getElementById("picture").src = "images/blue.png";
		document.getElementById("title").innerHTML = "Blue Chromatic Dragon";
		document.getElementById("description").innerHTML = "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air.";
	}else if(document.getElementById("picture").src.match("images/red.png") && document.getElementById("title").innerHTML == "Red Chromatic Dragon" && document.getElementById("description").innerHTML == "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs."){
		document.getElementById("picture").src = "images/blue.png";
		document.getElementById("title").innerHTML = "Blue Chromatic Dragon";
		document.getElementById("description").innerHTML = "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air.";
	}else if(document.getElementById("picture").src.match("images/green.png") && document.getElementById("title").innerHTML == "Green Chromatic Dragon" && document.getElementById("description").innerHTML == "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up."){
		document.getElementById("picture").src = "images/blue.png";
		document.getElementById("title").innerHTML = "Blue Chromatic Dragon";
		document.getElementById("description").innerHTML = "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air.";
	}else {
		
	}
}

function changeimg4 (el){ //Red Dragon
	if (document.getElementById("picture").src.match("images/tiamat.jpg") && document.getElementById("title").innerHTML == "Tiamat the Dragon Queen" && document.getElementById("description").innerHTML == "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power."){ //checks which picture it is
		document.getElementById("picture").src = "images/red.png"; //changes current image to Red Dragon
		document.getElementById("title").innerHTML = "Red Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs.";
	}else if(document.getElementById("picture").src.match("images/white.png") && document.getElementById("title").innerHTML == "White Chromatic Dragon" && document.getElementById("description").innerHTML == "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky."){
		document.getElementById("picture").src = "images/red.png";
		document.getElementById("title").innerHTML = "Red Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs.";
	}else if(document.getElementById("picture").src.match("images/black.png") && document.getElementById("title").innerHTML == "Black Chromatic Dragon" && document.getElementById("description").innerHTML == "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home."){
		document.getElementById("picture").src = "images/red.png";
		document.getElementById("title").innerHTML = "Red Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs.";
	}else if(document.getElementById("picture").src.match("images/blue.png") && document.getElementById("title").innerHTML == "Blue Chromatic Dragon" && document.getElementById("description").innerHTML == "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air."){
		document.getElementById("picture").src = "images/red.png";
		document.getElementById("title").innerHTML = "Red Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs.";
	}else if(document.getElementById("picture").src.match("images/green.png") && document.getElementById("title").innerHTML == "Green Chromatic Dragon" && document.getElementById("description").innerHTML == "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up."){
		document.getElementById("picture").src = "images/red.png";
		document.getElementById("title").innerHTML = "Red Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs.";
	}else {
		
	}
}

function changeimg5 (el){ //Green Dragon
	if (document.getElementById("picture").src.match("images/tiamat.jpg") && document.getElementById("title").innerHTML == "Tiamat the Dragon Queen" && document.getElementById("description").innerHTML == "Tiamat the Dragon Queen is the chief deity of evil dragonkind. She dwells on Avernus, the first layer of the Nine Hells. As a lesser god, Tiamat has the power to grant spells to her worshipers, though she is loath the share her power. She epitomizes the avarice of evil dragons, believing that the Multiverse and all its treasures will one day be hers and hers alone.  Tiamat is a gigantic dragon whose five heads reflect the forms of the chromatic dragons that worship her⁠—black, blue, green, red, and white. She is a terror on the battlefield, capable of annihilating whole armies with her five breath weapons, her formidable spellcasting, and her fearsome claws.  Tiamat’s most hated enemy is Bahamut the Platinum Dragon, with whom she shares the control of the faith of dragonkind. She also holds a special enmity for Asmodeus, who long ago stripped her of Avernus and who continues to curb the Dragon Queen’s power."){ //checks which picture, title, and description it is
		document.getElementById("picture").src = "images/green.png"; //changes current image to Green Dragon
		document.getElementById("title").innerHTML = "Green Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up.";
	}else if(document.getElementById("picture").src.match("images/white.png") && document.getElementById("title").innerHTML == "White Chromatic Dragon" && document.getElementById("description").innerHTML == "The smallest, least intelligent, and most animalistic of the chromatic dragons, white dragons dwell in frigid climes, favoring arctic areas or icy mountains.  They are vicious, cruel reptiles driven by hunger and greed.  A white dragon have feral eyes, a sleek profile, and a spined crest.  The scales of a wyrmling white dragon glisten pure white.  As the dragon ages, its sheen disappears and some of its scales begin to darken so that by the time it is old, it is mottled by patches of pale blue and light gray.  This patterning helps the dragon blend into the realms of ice and stone in which it hunts, and to fade from view when it soars across the cloud-filled sky."){
		document.getElementById("picture").src = "images/green.png";
		document.getElementById("title").innerHTML = "Green Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up.";
	}else if(document.getElementById("picture").src.match("images/black.png") && document.getElementById("title").innerHTML == "Black Chromatic Dragon" && document.getElementById("description").innerHTML == "The most evil-tempered and vile of the chromatic dragons, black dragons collect the wreckage and the treasures of fallen people. These dragons loathe seeing the weak prosper and revel in the collapse of humanoid kingdoms. They make their homes in fetid swamps and crumbling ruins where kingdoms once stood. With deep-socketed eyes and broad nasal openings, a black dragon’s face resembles a skull. The curving, segmented horns are bibe-colored near the base and darken to dead black at the tips. As black dragons age, the flesh around its horns and cheekbones deteriorates as though eaten by acid, leaving thin layers of a hide that enhance its skeletal appearance. A black dragon’s head is marked by spikes and horns. Its tongue is flat with a forked tip drooling slime whose acidic scent adds to the dragon’s reek of rotting vegetation and foul water.  When it hatches, a black dragon has glossy black scales.  As it ages, its scales become thicker and duller, helping it blend into the marshes and blasted ruins that are its home."){
		document.getElementById("picture").src = "images/green.png";
		document.getElementById("title").innerHTML = "Green Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up.";
	}else if(document.getElementById("picture").src.match("images/blue.png") && document.getElementById("title").innerHTML == "Blue Chromatic Dragon" && document.getElementById("description").innerHTML == "Vain and territorial, blue dragons soar through the skies over deserts, preying on caravans and plundering herds and settlements in the verdant lands beyond the desert’s reach.  These dragons can also be found in dry steppes, searing badlands, and rocky coasts.  The guard their territories against all potential competitors, especially brass dragons.  A blue dragon is recognized by its dramatic frilled ears and the massive ridged horns atop its blunt head.  Rows of spikes extend back from its nostrils to line its brow, and cluster on its jutting lower jaw.  A blue dragon’s scales vary in color from an iridescent azure to deep indigo, polished to a glossy finish by the desert sands.  As the dragon ages, its scales become thicker and harder, and its hide hums and crackles with electricity.  These effects intensify when the dragon is angry or about to attack, giving off an odor of ozone and dusty air."){
		document.getElementById("picture").src = "images/green.png";
		document.getElementById("title").innerHTML = "Green Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up.";
	}else if(document.getElementById("picture").src.match("images/red.png") && document.getElementById("title").innerHTML == "Red Chromatic Dragon" && document.getElementById("description").innerHTML == "The most covetous of the true dragons, red dragons tirelessly seek to increase their treasure hoard.  They are exceptionally vain, even for dragons, and their conceit is reflected in their proud bearing and their disdain for other creatures.  The odor of sulfur and pumice surrounds a red dragon, whose swept-back horns and spinal frill define its silhouette.  Its beaked snout vents smoke at all times, and its eyes dance with flame when it is angry.  Its wings are the longest of any chromatic dragon, and have a blue-black tint along the trailing edge the resembles metal burned by blue-fire.  The scales of a red dragon wyrmling are a bright glossy scarlet, turning a dull, deeper red and becoming as thick and strong as metal as the dragon ages.  Its pupils also fade as it ages, and the oldest red dragons have eyes that resemble molten lava orbs."){
		document.getElementById("picture").src = "images/green.png";
		document.getElementById("title").innerHTML = "Green Chromatic Dragon";
		document.getElementById("description").innerHTML = "The most cunning and treacherous of true dragons, green dragons use misdirection and trickery to get the upper hand against their enemies.  Nasty tempered and thoroughly evil, they take special pleasure in subverting and corrupting the good-hearted.  In the ancient forests they roam, green dragons demonstrate aggression that is often less about territory than it is about gaining power and wealth with as little effort as possible.  A green dragon is recognized by its curved jawline and the crest that begins near its eyes and continues down its spine, reaching full height just behind the skull.  A green dragon has no external ears but bears leathery spiked plates that run down the sides of its neck.  A wyrmling green dragon’s thin scales are a shade of green so dark as to appear nearly black.  As green dragons age, its scales grow larger and lighter, turning shades of the forest, emerald, and olive green to help it blend in with its wooded surroundings.  Its wings have a dappled pattern, darker near the leading edges and lighter towards the trailing edges.  A green dragon’s legs are longer in relation to its body than with any other dragon, enabling it to easily pass over underbrush and forest debris when it walks.  With its equally long neck, an older green dragon can peer over the tops of trees without rearing up.";
	}else {
		
	}
}
